spring:
  application:
    name: ews-signal-policy-engine
  datasource:
    url: jdbc:postgresql://localhost:5432/ews
    username: ews
    password: ews
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    streams:
      application-id: ews-signal-policy-engine

server:
  port: 8084
